### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by h266579110** [BeqaGurgenidze/CSWM#2]
Server will crash at someone attack to other.

**Comment by Kodpact** [comment]
Do you have bots on server?

**Comment by h266579110** [comment]
Yes I have bots in server

----- 回覆訊息 -----
寄件者： "Ghost" <notifications@github.com>
收件者： "BeqaGurgenidze/CSWM" <CSWM@noreply.github.com>
副本： "h266579110" <h266579110@hotmail.com>, "Author" <author@noreply.github.com>
主旨： [BeqaGurgenidze/CSWM] Server crash (#2)
日期： 週三, 6月 27 日, 2018 年 03:21


Do you have bots on server?

**Comment by BeqaGurgenidze** [comment]
@h266579110 If you are using ReGameDLL then i can not fix this issue. I reported this on ReGameDLL project.

**Comment by Kodpact** [comment]
@h266579110 Which type of bots you used ? (Metamod PodBot, ReGameDLL Bots or other...)

**Comment by h266579110** [comment]
I'm using ReGameDLL Bots

**Comment by Kodpact** [comment]
@h266579110  To me everythingis working fine. Are you sure crash is caused by CSWM. (If yes i need more information)

**Comment by h266579110** [comment]
it's will crash on after change map, first round start.

**Comment by Kodpact** [comment]
@h266579110  Are you using latest version (1.49 Beta)? cause this issue was in previous versions.

**Comment by h266579110** [comment]
I have latest ver. in the server.

**Comment by h266579110** [comment]
Btw, the server using:
AMX Mod X 1.8.3-dev+5154
ReHLDS with -pingboost 3 -bots
ReGameDLL

**Comment by Kodpact** [comment]
@h266579110 Please try only amxmodx (no other metamod plugins) and CSWM + Plugin That Creates Weapons.

**Comment by h266579110** [comment]
Still crash.


![3](https://user-images.githubusercontent.com/14806222/42131493-a4be9d80-7d35-11e8-9e9c-a1ea3b55b344.png)
![1](https://user-images.githubusercontent.com/14806222/42131494-a4e79a32-7d35-11e8-9aed-e8571e415621.png)
![2](https://user-images.githubusercontent.com/14806222/42131495-a5106a5c-7d35-11e8-9c61-147dff94c5c0.png)

**Comment by Kodpact** [comment]
@h266579110 Tested with these settings. Still no crash.

**Comment by h266579110** [comment]
Recompile weapons source code and fixed.
But after map change OICW secondary attack will crash server (no precache?)

**Comment by Kodpact** [comment]
@h266579110 Yes, i fixed that in 1.5 (Upcoming version)

> Recompile weapons source code and fixed.

Can you provide more information about fix.

**Comment by luisbustalu** [comment]
@ModderGhost, I would like to re-open this issue because this exact problem is happening to me. I'm testing with a real basic weapon, [cswm_test.zip](https://github.com/ModderGhost/CSWM/files/3202778/cswm_test.zip).

Every time I do damage, with or without the weapon in my hands, the server crashes. Even if I didn't register any weapon, but CSWM is enabled, server crashes.

I'm using ReHLDS 3.4.0.668-dev and Yet Another POD-Bot 2.9 (Build: 5395). I hope this could be fixed, I want to use this module to a project I'm doing. Thanks!

**Comment by Kodpact** [comment]
unfortunately i cannot fix that bug
