### ISSUE TITLE
[Request] Please need to be able to use 3,4,5 slots.

### ISSUE THREAD

**Issue by AoiKagase** [BeqaGurgenidze/CSWM#6]
I want to create a weapon to replace Knife/Grenade/C4.

I am currently working on my own plug-in to change C4 to Claymore and Knife to defibrillator.
This is working fine, but if you can make it happen in your module it will be easier to manage and will drastically reduce the amount of code.

Best regards.

**Comment by Nord1cWarr1or** [comment]
@AoiKagase why I can't open issue on your fork?
